version: "2.3"
services:
  jupyter:
    image: peinan/nlp-jp-gpu:latest
    user: root
    ports:
      - "8088:8888"
      - "6006:6006"
    volumes:
      - ${HOME}:/user
    working_dir: /user
    runtime: nvidia
    ipc: host
    environment:
      - GRANT_SUDO=yes
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    restart: always
    command: jupyter lab

